/**
 * Auto-generated Ontology Types
 *
 * Generated from composed ontology features: core, blog, portfolio, shop
 * DO NOT EDIT THIS FILE MANUALLY - it will be regenerated
 *
 * Generated at: 2025-10-19T20:24:05.546Z
 */
// ============================================================================
// Thing Types (Entities)
// ============================================================================
/**
 * All available thing types in the current ontology composition
 * Total: 15 types
 */
export type ThingType = 'page' | 'user' | 'file' | 'link' | 'note' | 'blog_post' | 'blog_category' | 'project' | 'case_study' | 'product' | 'product_variant' | 'shopping_cart' | 'order' | 'discount_code' | 'payment' | 'contact_submission';
/**
 * Array of all thing types (useful for validation and iteration)
 */
export const THING_TYPES: readonly ThingType[] = ['page', 'user', 'file', 'link', 'note', 'blog_post', 'blog_category', 'project', 'case_study', 'product', 'product_variant', 'shopping_cart', 'order', 'discount_code', 'payment', 'contact_submission'] as const;
/**
 * Check if a string is a valid ThingType
 */
export function isThingType(value: string): value is ThingType {
  return THING_TYPES.includes(value as ThingType);
}
// ============================================================================
// Connection Types (Relationships)
// ============================================================================
/**
 * All available connection types in the current ontology composition
 * Total: 11 types
 */
export type ConnectionType = 'created_by' | 'updated_by' | 'viewed_by' | 'favorited_by' | 'posted_in' | 'belongs_to_portfolio' | 'purchased' | 'in_cart' | 'variant_of' | 'ordered' | 'paid_for';
/**
 * Array of all connection types (useful for validation and iteration)
 */
export const CONNECTION_TYPES: readonly ConnectionType[] = ['created_by', 'updated_by', 'viewed_by', 'favorited_by', 'posted_in', 'belongs_to_portfolio', 'purchased', 'in_cart', 'variant_of', 'ordered', 'paid_for'] as const;
/**
 * Check if a string is a valid ConnectionType
 */
export function isConnectionType(value: string): value is ConnectionType {
  return CONNECTION_TYPES.includes(value as ConnectionType);
}
// ============================================================================
// Event Types
// ============================================================================
/**
 * All available event types in the current ontology composition
 * Total: 18 types
 */
export type EventType = 'thing_created' | 'thing_updated' | 'thing_deleted' | 'thing_viewed' | 'blog_post_published' | 'blog_post_viewed' | 'project_viewed' | 'product_added_to_cart' | 'cart_updated' | 'cart_abandoned' | 'order_placed' | 'order_fulfilled' | 'order_shipped' | 'order_delivered' | 'payment_processed' | 'payment_failed' | 'product_viewed' | 'discount_applied' | 'contact_submitted';
/**
 * Array of all event types (useful for validation and iteration)
 */
export const EVENT_TYPES: readonly EventType[] = ['thing_created', 'thing_updated', 'thing_deleted', 'thing_viewed', 'blog_post_published', 'blog_post_viewed', 'project_viewed', 'product_added_to_cart', 'cart_updated', 'cart_abandoned', 'order_placed', 'order_fulfilled', 'order_shipped', 'order_delivered', 'payment_processed', 'payment_failed', 'product_viewed', 'discount_applied', 'contact_submitted'] as const;
/**
 * Check if a string is a valid EventType
 */
export function isEventType(value: string): value is EventType {
  return EVENT_TYPES.includes(value as EventType);
}
// ============================================================================
// Feature Information
// ============================================================================
/**
 * Features included in this ontology composition
 */
export const ENABLED_FEATURES = ["core","blog","portfolio","shop"] as const;
/**
 * Ontology composition metadata
 */
export const ONTOLOGY_METADATA = {
  features: ENABLED_FEATURES,
  thingTypeCount: 15,
  connectionTypeCount: 11,
  eventTypeCount: 18,
  generatedAt: '2025-10-19T20:24:05.547Z',
} as const;
// ============================================================================
// Type Guards
// ============================================================================
/**
 * Type guard for any ontology type
 */
export function isValidOntologyType(
  dimension: 'thing' | 'connection' | 'event',
  value: string
): boolean {
  switch (dimension) {
    case 'thing':
      return isThingType(value);
    case 'connection':
      return isConnectionType(value);
    case 'event':
      return isEventType(value);
    default:
      return false;
  }
}
/**
 * Get all types for a specific dimension
 */
export function getTypesForDimension(
  dimension: 'thing' | 'connection' | 'event'
): readonly string[] {
  switch (dimension) {
    case 'thing':
      return THING_TYPES;
    case 'connection':
      return CONNECTION_TYPES;
    case 'event':
      return EVENT_TYPES;
    default:
      return [];
  }
}
// ============================================================================
// Feature Breakdown
// ============================================================================
/**
 * Feature: core
 * Core ontology always present in every ONE installation
 *
 * Thing Types: page, user, file, link, note
 * Connection Types: created_by, updated_by, viewed_by, favorited_by
 * Event Types: thing_created, thing_updated, thing_deleted, thing_viewed
 */
/**
 * Feature: blog
 * Blog and content publishing
 *
 * Thing Types: blog_post, blog_category
 * Connection Types: posted_in
 * Event Types: blog_post_published, blog_post_viewed
 */
/**
 * Feature: portfolio
 * Portfolio and project showcase
 *
 * Thing Types: project, case_study
 * Connection Types: belongs_to_portfolio
 * Event Types: project_viewed
 */
/**
 * Feature: shop
 * E-commerce and online store functionality
 *
 * Thing Types: product, product_variant, shopping_cart, order, discount_code, payment
 * Connection Types: purchased, in_cart, variant_of, ordered, paid_for
 * Event Types: product_added_to_cart, cart_updated, cart_abandoned, order_placed, order_fulfilled, order_shipped, order_delivered, payment_processed, payment_failed, product_viewed, discount_applied
 */
// ============================================================================
// Usage Examples
// ============================================================================
/**
 * Example: Validate thing type at runtime
 *
 * @example
 * const type = 'page';
 * if (isThingType(type)) {
 *   // TypeScript knows this is a valid ThingType
 *   console.log('Valid thing type:', type);
 * }
 */
/**
 * Example: Iterate over all thing types
 *
 * @example
 * for (const type of THING_TYPES) {
 *   console.log('Thing type:', type);
 * }
 */
/**
 * Example: Check if connection type exists
 *
 * @example
 * const connectionType = 'created_by';
 * if (isConnectionType(connectionType)) {
 *   // Safe to use
 * }
 */
/**
 * Example: Validate event type
 *
 * @example
 * const eventType = 'thing_created';
 * if (isEventType(eventType)) {
 *   // TypeScript infers correct type
 * }
 */
